# This is a basic workflow to help you get started with Actions

name: msteams-webhook

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the main branch
on:
  pull_request:
    branches: [ main ]
    types: [ assigned, opened, edited, closed, reopened, synchronize, ready_for_review, review_requested ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  webhook:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Workflow Webhook Action
        uses: dhollerbach/github-action-send-message-to-ms-teams@1.0.10
        with:
          webhook: ${{secrets.MSTEAMS_WEBHOOK_URL}}
          message: '<a href="https://github.com/SiecFirma/WebScraper/pull/${{github.event.number}}">https://github.com/SiecFirma/WebScraper/pull/${{github.event.number}}</a>'
